version: '3.8'

services:

  redis:
    restart: unless-stopped
    image: redis:latest
    ports:
      - "9595:6379"

  wsserver:
    restart: unless-stopped
    build:
      context: ./wsserver
      dockerfile: Dockerfile
    env_file:
      - monitor/.env
    depends_on:
      - redis
    ports:
      - "12000:12000"
    command: >
      sh -c "python ws_server.py & 
             python ws_relay_from_redis.py"

  celery:
    restart: unless-stopped
    build:
      context: ./monitor
      dockerfile: Dockerfile
    env_file:
      - monitor/.env
    depends_on:
      - redis
    command: >
      sh -c "celery -A celeryapps worker --loglevel=info"
    volumes:
      - /Users/iangabaraev/wav/:/app/wav/

  monitoring:
    restart: unless-stopped
    build:
      context: ./monitor
      dockerfile: Dockerfile
    env_file:
      - monitor/.env
    depends_on:
      - redis
    command: >
      sh -c "python monitor.py"
