version: '3.8'

services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  wsserver:
    build:
      context: ./wsserver
      dockerfile: Dockerfile
    env_file:
      - monitor/.env
    depends_on:
      - redis
    ports:
      - "12000:12000"
    command: >
      sh -c "python ws_server.py & 
             python ws_relay_from_redis.py"

  celery:
    build:
      context: ./monitor
      dockerfile: Dockerfile
    env_file:
      - monitor/.env
    depends_on:
      - redis
    command: >
      sh -c "celery -A celeryapps worker --loglevel=info"

  monitoring:
    build:
      context: ./monitor
      dockerfile: Dockerfile
    env_file:
      - monitor/.env
    depends_on:
      - redis
    command: >
      sh -c " python monitor.py"
