version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "7979:6379" # expose port 6999 on the host and map it to 6379 on the container

  wsserver:
    build:
      context: ../wsserver
      dockerfile: ../wsserver/Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "12000:12000" # expose port 6999 on the host and map it to 6379 on the container
    command: >
      sh -c "python ws_server.py & 
             python ws_relay_from_redis.py"

  monitoring:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
    command: >
      sh -c "python celeryapps.py & 
             python monitor.py"
